#!/bin/bash

echo TOOLCHAIN used is gcc-linaro-6.3.1-2017.02-i686_arm-linux-gnueabi
if [ -e ../gcc-linaro-6.3.1-2017.02-i686_arm-linux-gnueabi/bin ]
then
	echo "already exists"
else
	wkdir="$pwd"
	cd ../
	wget https://releases.linaro.org/components/toolchain/binaries/6.3-2017.02/arm-linux-gnueabi/gcc-linaro-6.3.1-2017.02-i686_arm-linux-gnueabi.tar.xz
	tar xf gcc-linaro-6.3.1-2017.02-i686_arm-linux-gnueabi.tar.xz
	cd "$wkdir"
fi
mkdir ../output-32
make mrproper O=../output-32
make clean O=../output-32
export ARCH=arm
export CROSS_COMPILE=../gcc-linaro-6.3.1-2017.02-i686_arm-linux-gnueabi/bin/arm-linux-gnueabi-
ARCH=arm make O=../output-32 k62v1_32_bsp_defconfig
ARCH=arm make -j2 O=../output-32 2> ../error

