#!/bin/bash

cd /home/v-user/android/Blu_vivo-xl4/VivoXL4-kernel-4.9
#make mrproper
make mrproper O=/home/v-user/android/Blu_vivo-xl4/output-32
make clean O=/home/v-user/android/Blu_vivo-xl4/output-32
#make ARCH=arm distclean
export ARCH=arm
export CROSS_COMPILE=/home/v-user/android/compiler/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-
#export CROSS_COMPILE=/home/v-user/android/google-gcc/arm-eabi-4.8/bin/arm-eabi-
#export CROSS_COMPILE=/home/v-user/android/built-tool/arm-linux-gnueabi/bin/arm-eabi-
#export CROSS_COMPILE=/home/v-user/android/google-gcc/arm-eabi-4.7/bin/arm-eabi-
#ARCH=arm make O=/home/v-user/android/Blu_vivo-xl4/output-32 k62mv1_bsp_defconfig
#ARCH=arm make O=/home/v-user/android/Blu_vivo-xl4/output-32 k62v1_32_bsp_defconfig
#ARCH=arm make O=/home/v-user/android/Blu_vivo-xl4/output-32 k62v1_bsp_defconfig
ARCH=arm make O=/home/v-user/android/Blu_vivo-xl4/output-32 k65v1_bsp_defconfig
ARCH=arm make -j2 O=/home/v-user/android/Blu_vivo-xl4/output-32

